/* Banco local do jogo. Cada item tem quatro opções e a posição correta é zero-based. */
(() => {
  const raw = {
    'Personagens Bíblicos': [
      ['fácil','Quem construiu a arca para salvar sua família do dilúvio?','Abraão|Noé|Moisés|Davi',1,'Noé recebeu instruções de Deus para construir a arca e preservar sua família e os animais.','Gênesis 6:14-22'],
      ['fácil','Quem foi o primeiro homem, segundo Gênesis?','Adão|Enoque|Noé|Sete',0,'Adão foi formado do pó da terra e recebeu o fôlego de vida.','Gênesis 2:7'],
      ['fácil','Quem derrotou Golias com uma funda e uma pedra?','Saul|Jônatas|Davi|Salomão',2,'Davi confiou no Senhor e venceu o guerreiro filisteu com uma pedra.','1 Samuel 17:49-50'],
      ['fácil','Qual profeta foi engolido por um grande peixe?','Elias|Jonas|Amós|Miqueias',1,'Jonas passou três dias e três noites no ventre do grande peixe.','Jonas 1:17'],
      ['fácil','Quem liderou os israelitas na saída do Egito?','Josué|Arão|Moisés|Calebe',2,'Moisés conduziu o povo para fora do Egito, sob a direção de Deus.','Êxodo 3:10'],
      ['médio','Qual era o nome da esposa de Abraão?','Rebeca|Sara|Raquel|Lia',1,'Sara deu à luz Isaque na velhice, conforme a promessa de Deus.','Gênesis 17:15-19'],
      ['médio','Quem interpretou os sonhos do faraó no Egito?','José|Daniel|Neemias|Ezequiel',0,'José interpretou os sonhos das vacas e espigas e aconselhou a armazenar alimento.','Gênesis 41:25-36'],
      ['médio','Qual juiz de Israel ficou conhecido por sua grande força?','Gideão|Sansão|Jefté|Otniel',1,'Sansão recebeu força extraordinária enquanto mantivesse seu voto nazireu.','Juízes 14:5-6'],
      ['médio','Quem sucedeu Moisés na liderança de Israel?','Calebe|Arão|Josué|Eleazar',2,'Josué conduziu o povo através do Jordão para a terra prometida.','Josué 1:1-2'],
      ['médio','Que jovem hebreu foi lançado na cova dos leões?','Sadraque|Daniel|Ezequiel|Esdras',1,'Daniel foi protegido por Deus na cova dos leões.','Daniel 6:16-23'],
      ['difícil','Qual era o nome do pai de João Batista?','Anás|Zacarias|Simeão|Jairo',1,'Zacarias era sacerdote e recebeu a notícia do nascimento de João.','Lucas 1:5-13'],
      ['difícil','Qual filho de Jacó recebeu uma túnica especial de seu pai?','Benjamim|Rúben|José|Judá',2,'Jacó deu a José uma túnica longa, sinal de seu carinho especial.','Gênesis 37:3'],
      ['difícil','Quem sucedeu Elias como profeta?','Eliseu|Isaías|Jeremias|Miqueias',0,'Eliseu pediu porção dobrada do espírito de Elias e continuou seu ministério.','2 Reis 2:9-15'],
      ['difícil','Qual rei pediu sabedoria a Deus em vez de riquezas?','Ezequias|Davi|Salomão|Josias',2,'Salomão pediu discernimento para governar o povo com justiça.','1 Reis 3:9-12'],
      ['difícil','Qual era o nome hebraico de Ester?','Hadassa|Miriã|Tamar|Abigail',0,'Hadassa era o nome hebraico de Ester; ela se tornou rainha da Pérsia.','Ester 2:7']
    ],
    'Heróis e Heroínas da Fé': [
      ['fácil','Qual mulher se tornou rainha e intercedeu por seu povo?','Rute|Ester|Débora|Marta',1,'Ester arriscou a vida ao se apresentar ao rei para salvar os judeus.','Ester 4:14-16'],
      ['fácil','Quem foi a sogra de Rute?','Noemi|Orfa|Ana|Mical',0,'Rute permaneceu com Noemi e adotou o povo e o Deus de sua sogra.','Rute 1:16'],
      ['fácil','Qual mulher julgava Israel debaixo de uma palmeira?','Jael|Débora|Miriã|Hulda',1,'Débora era profetisa e juíza; ela convocou Baraque para enfrentar Sísera.','Juízes 4:4-6'],
      ['fácil','Quem derrotou os midianitas com apenas 300 homens?','Sansão|Gideão|Jefté|Saul',1,'Deus reduziu o exército de Gideão para que a vitória fosse claramente atribuída a Ele.','Juízes 7:7'],
      ['fácil','Qual jovem moabita declarou lealdade a Noemi?','Ester|Rute|Raabe|Orfa',1,'Rute disse que o povo de Noemi seria seu povo e o Deus dela seria seu Deus.','Rute 1:16'],
      ['médio','Quem escondeu os espias israelitas em Jericó?','Raabe|Jael|Débora|Abigail',0,'Raabe protegeu os espias e pediu segurança para sua família.','Josué 2:1-6'],
      ['médio','Qual juiz fez um voto precipitado antes da batalha?','Gideão|Jefté|Sansão|Otniel',1,'Jefté fez um voto impensado antes de enfrentar os amonitas.','Juízes 11:30-35'],
      ['médio','Quem matou Sísera com uma estaca de tenda?','Débora|Jael|Ester|Mical',1,'Jael derrotou Sísera, comandante do exército cananeu.','Juízes 4:21'],
      ['médio','Qual profetisa foi consultada durante o reinado de Josias?','Miriã|Hulda|Ana|Débora',1,'Hulda confirmou a mensagem do livro da Lei encontrado no templo.','2 Reis 22:14-20'],
      ['médio','Qual mulher orou por um filho e depois o dedicou ao Senhor?','Ana|Sara|Rebeca|Raquel',0,'Ana cumpriu sua promessa e levou Samuel para servir no templo.','1 Samuel 1:10-28'],
      ['difícil','Quem foi o parente resgatador que se casou com Rute?','Boaz|Elimeleque|Obede|Malom',0,'Boaz cumpriu o papel de resgatador da família de Elimeleque.','Rute 4:9-13'],
      ['difícil','Qual juiz canhoto matou Eglom, rei de Moabe?','Sangar|Eúde|Tola|Jair',1,'Eúde usou uma espada curta e surpreendeu o rei Eglom.','Juízes 3:15-21'],
      ['difícil','Qual era a profissão de Jael, esposa de Héber?','Pastora|Tecelã|Nômade queneia|Sacerdotisa',2,'Jael pertencia ao grupo dos queneus, que vivia em tendas.','Juízes 4:17'],
      ['difícil','Quem liderou o cântico de vitória após a travessia do mar?','Miriã|Débora|Ester|Hulda',0,'Miriã, irmã de Moisés, conduziu as mulheres com tamborins e dança.','Êxodo 15:20-21'],
      ['difícil','Qual mulher sábia impediu Davi de se vingar de Nabal?','Abigail|Bate-Seba|Mical|Abisague',0,'Abigail levou provisões a Davi e o convenceu a não derramar sangue por vingança.','1 Samuel 25:23-33']
    ],
    'Nascimentos Importantes': [
      ['fácil','Qual filho nasceu de Abraão e Sara na velhice?','Ismael|Isaque|Jacó|Esaú',1,'Isaque nasceu conforme a promessa de Deus, apesar da idade avançada do casal.','Gênesis 21:1-3'],
      ['fácil','Quem nasceu de Isabel e Zacarias e preparou o caminho para Jesus?','João Batista|Tiago|André|Estêvão',0,'João Batista pregou arrependimento e anunciou a chegada do Messias.','Lucas 1:57-60'],
      ['fácil','Em que cidade nasceu Jesus?','Nazaré|Jerusalém|Belém|Jericó',2,'Jesus nasceu em Belém, cidade de Davi, durante o recenseamento.','Lucas 2:4-7'],
      ['fácil','Qual anjo anunciou a Maria que ela teria um filho?','Miguel|Gabriel|Rafael|Uriel',1,'Gabriel anunciou que Maria conceberia Jesus pelo poder do Espírito Santo.','Lucas 1:26-31'],
      ['fácil','Quem recebeu o nome de Isaque, que significa “ele ri”?','Filho de Abraão e Sara|Filho de Jacó e Raquel|Filho de Davi e Bate-Seba|Filho de Zacarias e Isabel',0,'O nome Isaque recordava o riso de Abraão e Sara diante da promessa.','Gênesis 17:17-19'],
      ['médio','Quem era a mãe de Samuel?','Penina|Ana|Abigail|Mical',1,'Ana pediu um filho ao Senhor e deu à luz Samuel.','1 Samuel 1:20'],
      ['médio','Qual filho de Raquel nasceu quando ela morreu?','José|Benjamim|Levi|Judá',1,'Raquel morreu ao dar à luz Benjamim, cujo nome foi mudado por Jacó.','Gênesis 35:16-18'],
      ['médio','Que sinal foi dado aos pastores para reconhecerem o bebê Jesus?','Uma estrela sobre o templo|Um bebê envolto em faixas numa manjedoura|Um anjo junto ao palácio|Uma coluna de fogo',1,'Os pastores encontrariam o menino envolto em faixas e deitado numa manjedoura.','Lucas 2:12'],
      ['médio','Quem era a mãe de Moisés?','Joquebede|Miriã|Zípora|Séfora',0,'Joquebede escondeu Moisés por três meses e depois o colocou num cesto no rio.','Êxodo 6:20; 2:1-3'],
      ['médio','Qual casal teve gêmeos chamados Esaú e Jacó?','Abraão e Sara|Isaque e Rebeca|Jacó e Lia|Elcana e Ana',1,'Isaque orou por Rebeca, que concebeu os gêmeos Esaú e Jacó.','Gênesis 25:21-26'],
      ['difícil','Qual era o nome do filho de Fineias que nasceu quando a arca foi capturada?','Icabô|Obede-Edom|Abias|Mefibosete',0,'A mãe chamou o menino Icabô, dizendo que a glória havia partido de Israel.','1 Samuel 4:19-22'],
      ['difícil','Qual filho nasceu a Tamar após a história com Judá?','Perez|Zerá|Er|Onã',0,'Tamar deu à luz gêmeos; Perez nasceu primeiro, rompendo adiante de Zerá.','Gênesis 38:27-30'],
      ['difícil','Em qual tribo nasceu o profeta Samuel?','Judá|Efraim (região montanhosa)|Benjamim|Levi',1,'Elcana era de Ramataim-Zofim, na região montanhosa de Efraim.','1 Samuel 1:1'],
      ['difícil','Qual nome o anjo mandou dar ao filho de Zacarias e Isabel?','Elias|João|Zacarias|Samuel',1,'O anjo declarou que ele deveria ser chamado João.','Lucas 1:13'],
      ['difícil','Qual rei tentou matar o menino Jesus após ouvir os magos?','Herodes, o Grande|Herodes Antipas|Pilatos|César Augusto',0,'Herodes ordenou a morte dos meninos de Belém por temer o novo rei.','Mateus 2:1-16']
    ],
    'Mortes e Sepultamentos': [
      ['fácil','Onde Abraão sepultou Sara?','Caverna de Macpela|Monte Sinai|Túmulo de Raquel|Vale de Cedrom',0,'Abraão comprou a caverna de Macpela, em Hebrom, para sepultar Sara.','Gênesis 23:19-20'],
      ['fácil','Qual patriarca foi sepultado na caverna de Macpela?','Moisés|Jacó|Samuel|Elias',1,'Jacó pediu para ser sepultado junto a Abraão, Isaque e suas esposas.','Gênesis 49:29-33; 50:13'],
      ['fácil','Quem foi apedrejado por testemunhar sobre Jesus?','Estêvão|Barnabé|Filipe|Silas',0,'Estêvão foi o primeiro mártir cristão mencionado no livro de Atos.','Atos 7:58-60'],
      ['fácil','Como morreu Golias?','Afogado|Decapitado por Davi|Atingido por uma lança de Saul|Em batalha contra Jônatas',1,'Davi derrubou Golias com uma pedra e usou a espada do próprio gigante.','1 Samuel 17:49-51'],
      ['fácil','Quem morreu ao tocar na arca da aliança durante o transporte?','Uzá|Obede-Edom|Abinadabe|Fineias',0,'Uzá estendeu a mão para segurar a arca e morreu por sua irreverência.','2 Samuel 6:6-7'],
      ['médio','Qual rei morreu após ser ferido por uma flecha em Ramote-Gileade?','Acabe|Jeú|Acazias|Jorão',0,'Acabe foi atingido apesar de ter se disfarçado durante a batalha.','1 Reis 22:34-37'],
      ['médio','Onde José pediu para que seus ossos fossem levados?','Belém|Canaã|Egito para Babilônia|Jerusalém',1,'Antes de morrer, José fez os israelitas jurarem que levariam seus ossos quando Deus os visitasse.','Gênesis 50:24-26'],
      ['médio','Quem morreu e foi sepultada sob um carvalho perto de Betel?','Débora, ama de Rebeca|Miriã|Raquel|Hulda',0,'O lugar recebeu o nome Alom-Bacute, “carvalho do pranto”.','Gênesis 35:8'],
      ['médio','Qual discípula morreu em Jope e foi ressuscitada por Pedro?','Lídia|Tabita (Dorcas)|Priscila|Febe',1,'Tabita era conhecida por suas boas obras; Pedro orou e ela voltou à vida.','Atos 9:36-41'],
      ['médio','Quem foi levado por Deus sem que a morte fosse descrita?','Enoque|Abraão|Moisés|Josué',0,'Gênesis diz que Enoque andou com Deus e desapareceu, pois Deus o tomou.','Gênesis 5:24'],
      ['difícil','Em que monte Moisés morreu?','Sinai|Nebo, na terra de Moabe|Carmelo|Gerizim',1,'Moisés morreu no monte Nebo e foi sepultado por Deus num local desconhecido.','Deuteronômio 34:1-6'],
      ['difícil','Quem matou Abner, comandante do exército de Saul?','Joabe|Abisai|Davi|Isbosete',0,'Joabe matou Abner à traição para vingar a morte de seu irmão Asael.','2 Samuel 3:27'],
      ['difícil','Onde foi sepultado João Batista, segundo Marcos?','No templo|Seus discípulos levaram o corpo e o puseram num túmulo|No palácio de Herodes|Em Betânia',1,'Após receberem a notícia, os discípulos de João levaram seu corpo e o sepultaram.','Marcos 6:29'],
      ['difícil','Qual rei de Judá foi sepultado na Cidade de Davi, mas não nos túmulos dos reis?','Uzias|Ezequias|Josias|Asa',0,'Por causa de sua lepra, Uzias foi sepultado perto dos túmulos reais, não dentro deles.','2 Crônicas 26:23'],
      ['difícil','Quem pediu o corpo de Jesus a Pilatos e o sepultou num túmulo novo?','Nicodemos|José de Arimateia|Simão de Cirene|José, irmão de Jesus',1,'José de Arimateia envolveu o corpo em lençol e o colocou em seu túmulo novo.','Mateus 27:57-60']
    ],
    'Datas e Tempos Bíblicos': [
      ['fácil','Quantos dias e noites choveu no início do dilúvio?','7|12|40|70',2,'Choveu sobre a terra durante quarenta dias e quarenta noites.','Gênesis 7:12'],
      ['fácil','Quantos anos os israelitas peregrinaram no deserto?','12|40|70|100',1,'A geração que saiu do Egito peregrinou quarenta anos no deserto.','Números 14:33-34'],
      ['fácil','Quantos dias Jesus jejuou no deserto?','7|12|30|40',3,'Jesus jejuou quarenta dias e foi tentado pelo diabo.','Mateus 4:1-2'],
      ['fácil','Em quantos dias, segundo Gênesis, Deus criou os céus e a terra antes do descanso?','5|6|7|40',1,'A narrativa descreve seis dias de criação e o descanso no sétimo.','Gênesis 1:31; 2:2'],
      ['fácil','Quantos dias durou a travessia do deserto até o monte Sinai?','3|7|11|40',2,'Deuteronômio registra que a jornada de Horebe a Cades-Barneia levou onze dias.','Deuteronômio 1:2'],
      ['médio','Por quantos anos Israel serviu ao rei da Babilônia, conforme Jeremias?','40|50|70|120',2,'Jeremias anunciou setenta anos de domínio babilônico.','Jeremias 25:11-12'],
      ['médio','Quantos dias os espiões exploraram Canaã?','7|12|40|70',2,'Doze espias percorreram a terra por quarenta dias.','Números 13:25'],
      ['médio','Por quantos anos Davi reinou sobre Israel?','20|30|40|70',2,'Davi reinou quarenta anos: sete em Hebrom e trinta e três em Jerusalém.','2 Samuel 5:4-5'],
      ['médio','Quantos anos tinha Jesus quando começou seu ministério, aproximadamente?','Cerca de 12|Cerca de 20|Cerca de 30|Cerca de 40',2,'Lucas informa que Jesus tinha cerca de trinta anos ao iniciar seu ministério.','Lucas 3:23'],
      ['médio','Quantos dias Jonas anunciou que faltavam para Nínive ser subvertida?','3|7|12|40',3,'Jonas proclamou que em quarenta dias Nínive seria destruída.','Jonas 3:4'],
      ['difícil','Quantas semanas foram determinadas na profecia de Daniel sobre seu povo?','7|62|70|77',2,'A profecia menciona setenta semanas; a interpretação do período varia entre tradições.','Daniel 9:24'],
      ['difícil','Quantos anos Israel foi oprimido por Jabim antes de Débora?','7|18|20|40',2,'Jabim oprimiu Israel por vinte anos antes da libertação conduzida por Débora e Baraque.','Juízes 4:3'],
      ['difícil','Quantos anos Salomão levou para construir o templo?','3|7|12|20',1,'A construção do templo durou sete anos.','1 Reis 6:37-38'],
      ['difícil','Quantos dias o povo rodeou Jericó antes de seus muros caírem?','6|7|12|40',1,'No sétimo dia, Israel rodeou a cidade sete vezes e os muros caíram.','Josué 6:3-5,15-20'],
      ['difícil','Quanto tempo durou a fome anunciada por Elias em Israel?','1 ano|2 anos|3 anos e 6 meses|7 anos',2,'A seca durou três anos e seis meses, segundo a narrativa e Tiago.','1 Reis 17:1; Tiago 5:17']
    ],
    'Animais da Bíblia': [
      ['fácil','Qual animal falou com Balaão?','Camelo|Jumenta|Leoa|Ovelha',1,'Deus abriu a boca da jumenta, que questionou Balaão no caminho.','Números 22:28-30'],
      ['fácil','Que animal forneceu lã para a metáfora de Jesus como Bom Pastor?','Cordeiro|Cabrito|Camelo|Pomba',0,'Jesus chamou a si mesmo de Bom Pastor, que dá a vida pelas ovelhas.','João 10:11'],
      ['fácil','Que animal engoliu Jonas?','Leão|Grande peixe|Águia|Crocodilo',1,'O texto hebraico diz “grande peixe”; “baleia” aparece em algumas traduções tradicionais.','Jonas 1:17'],
      ['fácil','Que animal atacou Sansão quando ele ia a Timna?','Urso|Leão|Lobo|Javali',1,'O Espírito do Senhor capacitou Sansão a despedaçar o leão.','Juízes 14:5-6'],
      ['fácil','Qual ave Noé soltou e que voltou com uma folha de oliveira?','Corvo|Pomba|Águia|Andorinha',1,'A pomba trouxe uma folha nova de oliveira, sinal de que as águas baixavam.','Gênesis 8:10-11'],
      ['médio','Que animal Deus providenciou no lugar de Isaque para o sacrifício?','Cordeiro|Carneiro preso pelos chifres|Bode|Novilho',1,'Abraão ofereceu um carneiro que encontrou preso pelos chifres num arbusto.','Gênesis 22:13'],
      ['médio','Quais animais puxaram o carro novo com a arca enviado pelos filisteus?','Duas vacas|Dois jumentos|Dois cavalos|Dois camelos',0,'Duas vacas com crias levaram o carro em direção a Bete-Semes.','1 Samuel 6:7-12'],
      ['médio','Que animal foi preparado para o filho pródigo na parábola?','Cordeiro cevado|Vitelo cevado|Pomba assada|Cabrito selvagem',1,'O pai mandou preparar o vitelo cevado para celebrar a volta do filho.','Lucas 15:23'],
      ['médio','Qual animal é associado à prudência em Mateus 10:16?','Leão|Serpente|Pomba|Raposa',1,'Jesus disse para seus discípulos serem prudentes como as serpentes.','Mateus 10:16'],
      ['médio','Que animal Jesus montou ao entrar em Jerusalém?','Cavalo|Jumentinho|Camelo|Carro de guerra',1,'Jesus entrou montado num jumentinho, cumprindo a profecia.','Marcos 11:7; Zacarias 9:9'],
      ['difícil','Quais animais aparecem no sonho do copeiro do faraó?','Três cestos e aves|Videira com três ramos|Sete vacas|Espigas de trigo',1,'O copeiro sonhou com uma videira de três ramos e taças de vinho.','Gênesis 40:9-13'],
      ['difícil','Qual animal simboliza o império medo-persa na visão de Daniel 8?','Leopardo|Carneiro com dois chifres|Bode|Leão alado',1,'O carneiro com dois chifres representa os reis da Média e da Pérsia.','Daniel 8:3-4,20'],
      ['difícil','Que animal carregou o pão e a carne para Elias junto ao ribeiro?','Pombas|Corvos|Águias|Cegonhas',1,'Corvos levavam alimento a Elias pela manhã e à tarde.','1 Reis 17:4-6'],
      ['difícil','Qual inseto João Batista comia no deserto?','Gafanhotos|Formigas|Abelhas|Grilos',0,'João se alimentava de gafanhotos e mel silvestre.','Mateus 3:4'],
      ['difícil','Quais animais representam os quatro seres viventes em Apocalipse?','Leão, boi, homem e águia|Cordeiro, cavalo, serpente e pomba|Urso, leopardo, bode e carneiro|Camelo, jumento, peixe e águia',0,'Os seres viventes tinham aparência de leão, novilho, homem e águia voando.','Apocalipse 4:6-8']
    ],
    'Livros e Autores da Bíblia': [
      ['fácil','Tradicionalmente, a autoria dos cinco primeiros livros é atribuída a quem?','Davi|Moisés|Salomão|Isaías',1,'A tradição bíblica associa a Lei a Moisés, embora sua formação textual seja estudada de várias formas.','Josué 8:31; Lucas 24:44'],
      ['fácil','Quem é tradicionalmente associado a muitos salmos?','Davi|Isaías|Lucas|Paulo',0,'Davi é associado a muitos salmos, embora o livro tenha autores diversos.','Salmos 3; 51'],
      ['fácil','Qual evangelho começa com “No princípio era o Verbo”?','Mateus|Marcos|Lucas|João',3,'O prólogo do Evangelho de João apresenta o Verbo que estava com Deus.','João 1:1'],
      ['fácil','Quem escreveu o livro de Atos dos Apóstolos?','Mateus|Lucas|Pedro|Tiago',1,'Atos é o segundo volume da obra de Lucas, dirigida a Teófilo.','Lucas 1:1-4; Atos 1:1'],
      ['fácil','Qual livro bíblico conta a história de uma rainha judia na Pérsia?','Ester|Rute|Juízes|Neemias',0,'O livro de Ester relata como a rainha salvou os judeus de um plano de extermínio.','Ester 1:1'],
      ['médio','Qual profeta escreveu lamentações após a queda de Jerusalém, segundo a tradição?','Jeremias|Ezequiel|Daniel|Oséias',0,'A tradição atribui Lamentações a Jeremias, embora o livro não identifique seu autor.','Lamentações 1:1'],
      ['médio','Qual evangelista era médico e companheiro de Paulo?','Marcos|Lucas|João|Mateus',1,'Paulo chama Lucas de médico amado em sua carta aos Colossenses.','Colossenses 4:14'],
      ['médio','Qual livro é associado ao apóstolo Paulo e trata da armadura de Deus?','Romanos|Efésios|Hebreus|Tiago',1,'Efésios 6 descreve a armadura de Deus na luta espiritual.','Efésios 6:10-18'],
      ['médio','Quem escreveu o livro do Apocalipse, conforme seu próprio testemunho?','Pedro|João|Paulo|Judas',1,'O autor se identifica como João e diz estar na ilha de Patmos.','Apocalipse 1:1,9'],
      ['médio','Qual livro é conhecido por apresentar muitos provérbios de Salomão?','Eclesiastes|Provérbios|Jó|Cantares',1,'Grande parte de Provérbios é atribuída a Salomão, com outras coleções também incluídas.','Provérbios 1:1; 10:1'],
      ['difícil','Quem é identificado como autor da carta a Filemom?','Pedro|Paulo|João|Tiago',1,'Paulo escreveu a Filemom em favor de Onésimo.','Filemom 1:1'],
      ['difícil','Qual livro afirma que “toda Escritura é inspirada por Deus”?','Hebreus|2 Timóteo|1 Pedro|Tito',1,'A carta exorta Timóteo a permanecer nas Escrituras que aprendeu.','2 Timóteo 3:14-16'],
      ['difícil','Qual livro do Antigo Testamento não menciona explicitamente o nome de Deus?','Ester|Rute|Jonas|Malaquias',0,'O nome de Deus não aparece explicitamente no texto de Ester, embora sua providência permeie a narrativa.','Ester 4:14'],
      ['difícil','Qual apóstolo é associado às três cartas que levam seu nome e falam sobre amor?','João|Pedro|Paulo|Judas',0,'As cartas de João enfatizam o amor, a verdade e a vida em Cristo.','1 João 4:7-8'],
      ['difícil','Quem escreveu a carta que diz: “a fé sem obras é morta”?','Judas|Tiago|Paulo|Pedro',1,'Tiago ensina que a fé viva se demonstra por obras.','Tiago 2:17']
    ],
    'Milagres e Parábolas': [
      ['fácil','Qual foi o primeiro sinal de Jesus no Evangelho de João?','Curar um cego|Transformar água em vinho|Andar sobre o mar|Multiplicar pães',1,'Jesus transformou água em vinho numa festa de casamento em Caná.','João 2:1-11'],
      ['fácil','Quantos pães e peixes foram usados para alimentar cinco mil homens?','Cinco pães e dois peixes|Sete pães e poucos peixes|Dois pães e cinco peixes|Doze pães e um peixe',0,'Um menino ofereceu cinco pães e dois peixes; todos comeram e sobraram cestos.','João 6:9-13'],
      ['fácil','Na parábola, quem ajudou o homem ferido na estrada?','Um sacerdote|Um samaritano|Um soldado|Um comerciante',1,'O samaritano cuidou do homem, enquanto outros passaram sem ajudar.','Lucas 10:30-37'],
      ['fácil','Quem Jesus ressuscitou depois de quatro dias no túmulo?','Jairo|Lázaro|Estêvão|Nicodemos',1,'Jesus chamou Lázaro para fora do túmulo em Betânia.','João 11:38-44'],
      ['fácil','O que o pai fez quando o filho pródigo voltou para casa?','Mandou-o embora|Recebeu-o com festa|Prendeu-o|Exigiu pagamento',1,'O pai correu ao encontro do filho, abraçou-o e celebrou sua volta.','Lucas 15:20-24'],
      ['médio','Quantos cestos de sobras ficaram após a alimentação dos cinco mil?','5|7|12|40',2,'Os discípulos recolheram doze cestos dos pedaços que sobraram.','Mateus 14:20'],
      ['médio','Qual parábola fala de sementes que caíram em diferentes tipos de solo?','O semeador|A dracma perdida|Os talentos|As dez virgens',0,'Os diferentes solos ilustram maneiras distintas de receber a palavra.','Mateus 13:3-9,18-23'],
      ['médio','O que Pedro encontrou na boca do primeiro peixe que pescou após a instrução de Jesus?','Uma pérola|Uma moeda de quatro dracmas|Uma chave|Um anel',1,'A moeda encontrada na boca do peixe pagou o imposto do templo por Jesus e Pedro.','Mateus 17:24-27'],
      ['médio','Qual discípulo andou sobre as águas em direção a Jesus?','João|Pedro|Tomé|André',1,'Pedro saiu do barco e caminhou sobre as águas, mas começou a afundar quando teve medo.','Mateus 14:28-31'],
      ['médio','Na parábola das dez virgens, quantas eram prudentes?','3|5|7|10',1,'Cinco virgens prudentes levaram azeite extra para suas lâmpadas.','Mateus 25:1-4'],
      ['difícil','Qual era o nome do servo do sumo sacerdote cuja orelha Pedro cortou?','Malco|Bartimeu|Clopas|Jairo',0,'João identifica como Malco o servo que teve a orelha cortada.','João 18:10'],
      ['difícil','Quantos leprosos voltaram para agradecer depois de serem curados?','Nenhum|Um|Três|Dez',1,'Somente um dos dez voltou para glorificar a Deus, e era samaritano.','Lucas 17:15-19'],
      ['difícil','Em qual tanque Jesus curou um homem enfermo havia 38 anos?','Siloé|Betesda|Gion|Sicar',1,'Jesus curou o homem junto ao tanque de Betesda, em Jerusalém.','João 5:2-9'],
      ['difícil','Na parábola, quantos talentos recebeu o servo que recebeu menos?','Um|Dois|Três|Cinco',0,'Um servo recebeu um talento e o escondeu em vez de fazê-lo render.','Mateus 25:14-18'],
      ['difícil','Qual profeta Jesus menciona como sinal ao comparar seus três dias com a experiência dele?','Elias|Jonas|Isaías|Moisés',1,'Jesus comparou sua permanência no sepulcro à experiência de Jonas no grande peixe.','Mateus 12:39-40']
    ],
    'Reis e Profetas de Israel e Judá': [
      ['fácil','Quem foi o primeiro rei de Israel?','Davi|Saul|Salomão|Roboão',1,'Saul foi ungido por Samuel como primeiro rei de Israel.','1 Samuel 10:1,24'],
      ['fácil','Qual profeta enfrentou os profetas de Baal no monte Carmelo?','Eliseu|Elias|Isaías|Samuel',1,'Elias desafiou os profetas de Baal e Deus respondeu com fogo.','1 Reis 18:20-39'],
      ['fácil','Quem construiu o primeiro templo em Jerusalém?','Davi|Salomão|Ezequias|Josias',1,'Salomão construiu o templo que seu pai Davi desejara edificar.','1 Reis 6:1,14'],
      ['fácil','Qual profeta ungiu Davi como rei?','Natã|Elias|Samuel|Gade',2,'Samuel ungiu Davi por ordem do Senhor, ainda jovem.','1 Samuel 16:1,12-13'],
      ['fácil','Qual rainha tomou o trono de Judá e perseguiu a família real?','Jezabel|Atalia|Bate-Seba|Maaca',1,'Atalia usurpou o trono, mas Joás foi escondido e preservado.','2 Reis 11:1-3'],
      ['médio','Qual rei de Judá encontrou o Livro da Lei durante reparos no templo?','Josias|Acaz|Manassés|Uzias',0,'O sacerdote Hilquias encontrou o livro, e Josias promoveu uma reforma.','2 Reis 22:8-13'],
      ['médio','Qual profeta confrontou Davi com a parábola da cordeirinha?','Elias|Natã|Samuel|Gade',1,'Natã contou uma parábola para confrontar Davi por seu pecado com Bate-Seba.','2 Samuel 12:1-7'],
      ['médio','Qual rei de Israel construiu uma capital em Samaria?','Onri|Acabe|Jeroboão|Jeú',0,'Onri comprou o monte Samaria e edificou ali uma cidade.','1 Reis 16:23-24'],
      ['médio','Qual profeta sucedeu Elias e pediu porção dobrada de seu espírito?','Miqueias|Eliseu|Amós|Oséias',1,'Eliseu recebeu o manto de Elias e continuou o ministério profético.','2 Reis 2:9-15'],
      ['médio','Qual rei ficou leproso após oferecer incenso no templo?','Uzias|Ezequias|Acaz|Jotão',0,'Uzias foi ferido com lepra por assumir uma função sacerdotal que não lhe cabia.','2 Crônicas 26:16-21'],
      ['difícil','Qual rei de Israel foi ferido por uma flecha ao tentar escapar disfarçado?','Acabe|Jeroboão II|Peca|Oséias',0,'Um arqueiro atirou ao acaso e feriu Acabe entre as juntas da armadura.','1 Reis 22:34-35'],
      ['difícil','Qual profeta anunciou que o rei Josias morreria em paz, sem ver a calamidade?','Hulda|Jeremias|Sofonias|Naum',0,'Hulda transmitiu a promessa de que Josias seria recolhido em paz antes do desastre.','2 Reis 22:18-20'],
      ['difícil','Qual rei de Judá removeu os lugares altos e confiou no Senhor?','Ezequias|Acaz|Manassés|Jeorão',0,'Ezequias removeu altares idólatras e confiou no Senhor durante a ameaça assíria.','2 Reis 18:3-7'],
      ['difícil','Qual profeta viu uma visão de um rolo voante?','Zacarias|Ageu|Joel|Habacuque',0,'Zacarias viu um rolo voante que simbolizava maldição sobre a terra.','Zacarias 5:1-4'],
      ['difícil','Qual rei de Israel reinou por apenas sete dias em Tirza?','Zinri|Ela|Pecaías|Salum',0,'Zinri tomou o trono e morreu quando o palácio foi incendiado durante o cerco.','1 Reis 16:15-18']
    ],
    'Lugares e Geografia Bíblica': [
      ['fácil','Em qual cidade Jesus nasceu?','Nazaré|Belém|Cafarnaum|Jericó',1,'Belém era conhecida como cidade de Davi e foi o local do nascimento de Jesus.','Lucas 2:4-7'],
      ['fácil','Em qual jardim Jesus orou antes de ser preso?','Éden|Getsêmani|Carmelo|Siloé',1,'Jesus orou no jardim do Getsêmani, no monte das Oliveiras.','Mateus 26:36'],
      ['fácil','Qual rio os israelitas atravessaram para entrar em Canaã?','Nilo|Jordão|Eufrates|Quisom',1,'O Jordão parou de correr enquanto o povo atravessava para a terra prometida.','Josué 3:14-17'],
      ['fácil','Em que monte Moisés recebeu os mandamentos?','Carmelo|Sinai|Nebo|Sião',1,'Moisés subiu ao monte Sinai e recebeu as palavras da aliança.','Êxodo 19:20; 20:1-17'],
      ['fácil','Qual cidade teve seus muros derrubados após Israel rodeá-la?','Ai|Jericó|Betel|Hebrom',1,'Os muros de Jericó caíram depois que o povo rodeou a cidade conforme a ordem divina.','Josué 6:20'],
      ['médio','Em qual cidade os discípulos foram chamados cristãos pela primeira vez?','Antioquia|Éfeso|Corinto|Roma',0,'Em Antioquia os discípulos foram chamados cristãos pela primeira vez.','Atos 11:26'],
      ['médio','Qual cidade era conhecida como a cidade de Davi?','Belém|Hebrom|Jerusalém|Siquém',2,'Davi conquistou a fortaleza de Sião e fez de Jerusalém sua cidade.','2 Samuel 5:7-9'],
      ['médio','Em qual ilha Paulo naufragou a caminho de Roma?','Chipre|Creta|Malta|Patmos',2,'Após o naufrágio, Paulo e os demais chegaram à ilha chamada Malta.','Atos 28:1'],
      ['médio','Qual cidade ficava perto do poço onde Jesus conversou com a samaritana?','Sicar|Damasco|Cesareia|Jope',0,'O encontro ocorreu junto ao poço de Jacó, perto de Sicar, na Samaria.','João 4:5-7'],
      ['médio','Em qual montanha Elias confrontou os profetas de Baal?','Sinai|Carmelo|Hermom|Nebo',1,'O desafio público aconteceu no monte Carmelo.','1 Reis 18:19-20'],
      ['difícil','Qual era a capital do reino do norte após a divisão de Israel?','Samaria|Jerusalém|Hebrom|Damasco',0,'Samaria tornou-se capital do reino de Israel durante o reinado de Onri.','1 Reis 16:24'],
      ['difícil','Em qual cidade Paulo discursou no Areópago?','Corinto|Atenas|Éfeso|Filipos',1,'Paulo falou aos atenienses no Areópago sobre o Deus que eles desconheciam.','Atos 17:19-22'],
      ['difícil','Qual monte é tradicionalmente associado à transfiguração de Jesus?','Tabor|Sinai|Carmelo|Nebo',0,'Os evangelhos mencionam um monte alto sem nome; a tradição cristã frequentemente identifica Tabor.','Mateus 17:1-2'],
      ['difícil','Qual rio Naamã atravessou sete vezes para ser curado?','Jordão|Abana|Farpar|Nilo',0,'Eliseu mandou Naamã lavar-se sete vezes no Jordão.','2 Reis 5:10-14'],
      ['difícil','Para qual cidade Filipe foi enviado antes de encontrar o eunuco etíope?','Gaza|Samaria|Jope|Lida',0,'Um anjo orientou Filipe a seguir pelo caminho deserto que descia de Jerusalém a Gaza.','Atos 8:26']
    ],
    'Novo Testamento': [
      ['fácil','Quem batizou Jesus?','Pedro|João Batista|André|Nicodemos',1,'João Batista batizou Jesus no rio Jordão.','Mateus 3:13-17'],
      ['fácil','Qual discípulo traiu Jesus?','Judas Iscariotes|Tomé|Pedro|Filipe',0,'Judas identificou Jesus aos guardas com um beijo.','Mateus 26:14-16,47-49'],
      ['fácil','Quantos apóstolos Jesus escolheu?','7|10|12|40',2,'Jesus escolheu doze apóstolos para estarem com ele e serem enviados.','Marcos 3:13-19'],
      ['fácil','Quem negou Jesus três vezes antes do cantar do galo?','João|Pedro|Tiago|André',1,'Pedro negou conhecer Jesus e depois chorou amargamente.','Lucas 22:54-62'],
      ['fácil','Qual apóstolo era cobrador de impostos antes de seguir Jesus?','Mateus|João|Simão|Judas',0,'Jesus chamou Mateus da coletoria, e ele se levantou para segui-lo.','Mateus 9:9'],
      ['médio','Qual era o nome hebraico de Paulo?','Saulo|Silas|Simeão|Sérgio',0,'Antes de ser conhecido como Paulo, ele era chamado Saulo.','Atos 13:9'],
      ['médio','Em qual caminho Paulo teve uma visão de Jesus?','Damasco|Jericó|Emaús|Antioquia',0,'Saulo viajava para Damasco quando uma luz do céu o cercou.','Atos 9:3-6'],
      ['médio','Quem ajudou Jesus a carregar a cruz?','José de Arimateia|Simão de Cirene|Nicodemos|Bartimeu',1,'Os soldados obrigaram Simão de Cirene a carregar a cruz de Jesus.','Marcos 15:21'],
      ['médio','Qual discípulo duvidou da ressurreição até ver Jesus?','Tomé|Tiago|Mateus|Judas',0,'Tomé declarou que precisava ver as marcas antes de crer; Jesus apareceu a ele.','João 20:24-29'],
      ['médio','Em qual cidade Paulo e Silas cantaram na prisão?','Filipos|Roma|Éfeso|Corinto',0,'Na prisão de Filipos, eles oravam e cantavam quando ocorreu um terremoto.','Atos 16:22-26'],
      ['difícil','Qual casal explicou com mais exatidão o caminho de Deus a Apolo?','Priscila e Áquila|Ananias e Safira|Lídia e Lucas|Marta e Maria',0,'Priscila e Áquila ouviram Apolo e o instruíram melhor sobre o caminho de Deus.','Atos 18:24-26'],
      ['difícil','Quem foi escolhido para ocupar o lugar de Judas entre os apóstolos?','Matias|Barnabé|Silas|Estêvão',0,'Após oração e sorteio, Matias foi contado com os onze apóstolos.','Atos 1:23-26'],
      ['difícil','Qual jovem caiu de uma janela durante uma longa fala de Paulo?','Êutico|Timóteo|Trófimo|Onésimo',0,'Êutico caiu do terceiro andar, mas Paulo o abraçou e ele foi encontrado vivo.','Atos 20:7-12'],
      ['difícil','Qual centurião romano recebeu Pedro em Cesareia?','Cornélio|Júlio|Cláudio|Lísias',0,'Cornélio era piedoso e recebeu Pedro após uma visão que ampliou a missão aos gentios.','Atos 10:1-5,24'],
      ['difícil','Qual colaborador Paulo deixou em Creta para organizar as igrejas?','Tito|Timóteo|Tíquico|Crescente',0,'Paulo pediu a Tito que colocasse em ordem o que ainda faltava nas cidades de Creta.','Tito 1:4-5']
    ],
    'Antigo Testamento': [
      ['fácil','Qual foi o primeiro livro da Bíblia?','Êxodo|Gênesis|Levítico|Salmos',1,'Gênesis relata a criação, os patriarcas e o começo da história de Israel.','Gênesis 1:1'],
      ['fácil','Qual livro vem imediatamente depois de Gênesis?','Levítico|Números|Êxodo|Deuteronômio',2,'Êxodo conta a libertação dos israelitas do Egito.','Êxodo 1:1'],
      ['fácil','Qual livro narra a conquista de Jericó?','Juízes|Josué|Rute|1 Samuel',1,'O livro de Josué narra a entrada na terra e a queda de Jericó.','Josué 6:1-20'],
      ['fácil','Qual livro contém muitos cânticos e orações atribuídos a Davi?','Provérbios|Salmos|Jó|Cantares',1,'Salmos reúne cânticos, orações e poemas de vários autores.','Salmos 23; 51'],
      ['fácil','Qual é o último livro do Antigo Testamento na Bíblia protestante?','Zacarias|Malaquias|Ageu|Daniel',1,'Malaquias encerra a coleção do Antigo Testamento na ordem protestante comum.','Malaquias 4:5-6'],
      ['médio','Qual livro conta a história de uma moabita que se tornou ancestral de Davi?','Ester|Rute|Juízes|Esdras',1,'Rute casou-se com Boaz e tornou-se bisavó do rei Davi.','Rute 4:13-17'],
      ['médio','Qual livro descreve a reconstrução dos muros de Jerusalém?','Esdras|Neemias|Ageu|Ester',1,'Neemias liderou o povo na reconstrução dos muros da cidade.','Neemias 2:17-18; 6:15'],
      ['médio','Qual livro apresenta a visão do vale de ossos secos?','Isaías|Ezequiel|Daniel|Zacarias',1,'Ezequiel viu ossos secos que voltaram à vida, imagem da restauração de Israel.','Ezequiel 37:1-14'],
      ['médio','Em qual livro aparece a história de Jó?','Salmos|Jó|Provérbios|Eclesiastes',1,'Jó aborda sofrimento, fidelidade e a soberania de Deus.','Jó 1:1'],
      ['médio','Qual livro conta a construção do templo de Salomão?','1 Reis|Juízes|Rute|Neemias',0,'1 Reis descreve a construção e a dedicação do templo.','1 Reis 6:1-14; 8:1-11'],
      ['difícil','Qual profeta anunciou: “o justo viverá pela sua fé”?','Habacuque|Naum|Sofonias|Ageu',0,'Habacuque recebeu a resposta de que o justo viveria pela fé.','Habacuque 2:4'],
      ['difícil','Qual livro narra o desafio de Elias aos profetas de Baal?','2 Reis|1 Reis|1 Crônicas|Jeremias',1,'O confronto no monte Carmelo está registrado em 1 Reis.','1 Reis 18:20-40'],
      ['difícil','Qual livro descreve a visão de quatro animais que representam reinos?','Daniel|Ezequiel|Zacarias|Joel',0,'Daniel viu quatro grandes animais que simbolizavam reinos sucessivos.','Daniel 7:1-17'],
      ['difícil','Qual profeta anunciou que o governante de Israel viria de Belém?','Miqueias|Amós|Oséias|Joel',0,'Miqueias profetizou que de Belém sairia aquele que governaria Israel.','Miqueias 5:2'],
      ['difícil','Qual livro começa com “Vaidade de vaidades, tudo é vaidade”?','Provérbios|Eclesiastes|Jó|Cantares',1,'Eclesiastes reflete sobre a brevidade da vida e a busca por sentido.','Eclesiastes 1:2']
    ]
  };
  let id = 1;
  window.QUESTIONS = Object.entries(raw).flatMap(([categoria, items]) => items.map(([dificuldade, pergunta, options, correta, explicacao, referencia]) => ({
    id: id++, categoria, dificuldade, pergunta, alternativas: options.split('|'), correta, explicacao, referencia
  })));
  window.CATEGORIES = Object.keys(raw);
})();
